### PR TITLE
Check validateType returned value

### LINKED ISSUE #133: Check validateType returned value
As `validateType` method can return a `null` value, there should always be a check of that condition.

There are some cases where the code breaks due to a `Cannot read property 'errors' of null` error.

### PR DESCRIPTION
**Pull request by inigomarquinez**
### Fixed bug:
`validateType` method can return a null object, so the result needs to always be checked before reading the `valid` property. If the returned object is null, reading its `valid` property will throw an error.

### Context
- Close #133

### CODE REVIEW

**Comment by brodyd** [comment]
Can you remove the Package-lock file.  I've dropped it in my master and I'd rather not reintroduce it.  You may just need to refresh your branch from the origin again.

**Comment by inigomarquinez** [comment]
@brodyd I have removed `package-lock.json` file as requested.

**Comment by inigomarquinez** [comment]
Hello @brodyd . Is there anything else I can do to move on with this PR? Thank you!

**Comment by brodyd** [comment]
I’ll have it done later today.

**Comment by brodyd** [comment]
@inigomarquinez this has been merged and published.  Thank you for your PR and your efforts

**Pull request merged**
